spring:
  datasource:
    url: jdbc:mysql://localhost/hotel_model?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: BC6310
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:  # the fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080